### ISSUE TITLE
Tracking: Simple Carbon Optimization Recommendations

### ISSUE THREAD

**Issue by mkorbi** [carbonaut-cloud/carbonaut#31]
Implement first simple recommendations to optimize workload in reducing power consumption and emission causing.

- [ ] Filter relevant existing KPIs & discuss which data is needed to add more KPIs
- [ ]  Discuss & define how recommendations should get communicated (output of a CLI, or differently?)
- [ ]  Implement recommendation algorithm
