### ISSUE TITLE
Tracking: Continuous build & deploy 

### ISSUE THREAD

**Issue by mkorbi** [carbonaut-cloud/carbonaut#35]
We want to have from the beginning a clean and stable procedure to build, deploy and manage all artifacts.

- [ ] https://github.com/carbonaut-cloud/carbonaut/issues/40
- [x] https://github.com/carbonaut-cloud/carbonaut/issues/42
- [ ] https://github.com/carbonaut-cloud/carbonaut/issues/41
