### ISSUE TITLE
Tracking: carbon reporting

### ISSUE THREAD

**Issue by leonardpahlke** [carbonaut-cloud/carbonaut#39]
## What is needed:

- [ ] Investigate how to reports should look like and how they are getting used
- [ ] Define report schema (how the report is structured)
- [ ] Implement the reporter ([c/pkg/data/reporter](https://github.com/carbonaut-cloud/carbonaut/tree/main/pkg/data/reporter))
