### ISSUE TITLE
Tracking: Carbonaut database integration

### ISSUE THREAD

**Issue by leonardpahlke** [carbonaut-cloud/carbonaut#42]
## What is needed:

- [x] Investigate data model and which databases could fit
- [x] Investigate and define how the database should be hosted (container, CSP, K8s, all?) (see docs PR https://github.com/carbonaut-cloud/carbonaut-cloud.github.io/pull/14)
- [x] Implement: communicate to the database
- [ ] Document how to deploy the database
- [ ] Write E2E test and run it in CICD

**Comment by leonardpahlke** [comment]
we dont plan to host a database in our architecture anymore
