### ISSUE TITLE
Tracking: Integrate AWS 

### ISSUE THREAD

**Issue by leonardpahlke** [carbonaut-cloud/carbonaut#45]
## What is needed:

- [ ] Investigate how we can access AWS (APIs, SDKs...) (ref: https://github.com/carbonaut-cloud/carbonaut/issues/7)
- [ ] Investigate which services to contact / which APIs to use
- [ ] Extend carbonaut configuration to enable AWS (see: https://github.com/carbonaut-cloud/carbonaut/issues/8)
- [ ] Implement: get data from AWS
- [ ] Implement: translate aws data to generic data model (see: https://github.com/carbonaut-cloud/carbonaut/issues/6)
