### ISSUE TITLE
Tracking: Carbonaut data model

### ISSUE THREAD

**Issue by leonardpahlke** [carbonaut-cloud/carbonaut#47]
## What is needed:

- [x] Investigate which data is provided by CSP that could be useful for us
- [x] Investigate what we like to display and which KPIs are relevant
- [x] Define a generic data model for carbonaut
- [x] Implement the generic data model
- [x] Test the data model out (store CSP data and work with it) 
- [x] evaluate the data model for the next the version iteration

**Comment by leonardpahlke** [comment]
added https://github.com/carbonaut-cloud/carbonaut/tree/main/api/connector
