### ISSUE TITLE
Tracking: Carbon optimization recommendations

### ISSUE THREAD

**Issue by leonardpahlke** [carbonaut-cloud/carbonaut#57]
## What is needed:

- [ ] Filter relevant existing KPIs & discuss which data is needed to add more KPIs
- [ ] Discuss & define how recommendations should get communicated (output of a CLI, or differently?)
- [ ] Implement recommendation algorithm
