### ISSUE TITLE
Tracking: Add configuration to carbonaut

### ISSUE THREAD

**Issue by leonardpahlke** [carbonaut-cloud/carbonaut#59]
## What is needed:

It is needed to configure Carbonaut to specify various things like which CP to use and which services of the CP but also where to deploy the system (ports, ...). 

- [x] Investigate how to configure carbonaut (multiple options?) (config file, CLI, ...?)
- [x] Investigate which tools to use for configuration (like [viper](https://github.com/spf13/viper) for example)
- [x] Enable configuration in carbonaut (which can be easily extended later)
