### ISSUE TITLE
Carbonaut Connector Bootstrap

### ISSUE THREAD

**Issue by leonardpahlke** [carbonaut-cloud/carbonaut#62]
### What would you like to be added?

- [ ] connector configuration management
- [ ] connector plugin loading
- [ ] connector plugin start 
- [ ] connector metrics server

### Why is this needed?

Add core logic

### Relevant Kind label(s)

/kind epic
